# Imagem base
FROM node:22-alpine

# Diretório de trabalho
WORKDIR /app

# Copiar package.json e instalar dependências
COPY package*.json ./
RUN npm ci

# Copiar todo o código da aplicação
COPY . .

# Configurar variáveis de ambiente padrão
ENV PORT=5000
ENV NODE_ENV=production

# Expor porta da aplicação
EXPOSE 5000

# Comando de inicialização da aplicação
CMD ["npm", "run", "start:prod"]

