FROM node:22-alpine

RUN apk add --no-cache bash curl jq python3 py3-pip \
    && pip install --no-cache-dir awscli

WORKDIR /app
COPY package*.json ./
RUN npm ci
COPY . .

EXPOSE 443

CMD sh -c '\
  SECRET_JSON=$(aws secretsmanager get-secret-value --secret-id /medsafe/database-service/prod --query SecretString --output text) && \
  export DB_CONNECTION_STRING=$(echo $SECRET_JSON | jq -r ".DB_CONNECTION_STRING") && \
  export JWT_SECRET=$(echo $SECRET_JSON | jq -r ".JWT_SECRET") && \
  export DATABASE_SERVICE_X_AUTH_SERVICE_API_KEY=$(echo $SECRET_JSON | jq -r ".DATABASE_SERVICE_X_AUTH_SERVICE_API_KEY") && \
  npm start \
'
