Resources:

  DatabaseApiSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Permitir acesso à API
      VpcId: vpc-0d3b446d45264fea7
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: !Ref ApiPort
          ToPort: !Ref ApiPort
          CidrIp: !Ref AllowedIP
          
  DatabaseApiInstance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: !Ref InstanceType
      SecurityGroupIds:
        - !Ref DatabaseApiSecurityGroup
      ImageId: ami-0bde73fd629657a5
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          apt-get update -y
          apt-get install -y docker.io
          systemctl start docker
          systemctl enable docker
          
          docker pull usuario/medsafe-database-service:${DockerImageTag}
          docker stop medsafe-database-service || true
          docker rm medsafe-database-service || true
          docker run -d --name medsafe-database-service -p ${ApiPort}:${ApiPort} \
            -e DB_CONNECTION_STRING=${DbConnectionString} \
            usuario/medsafe-database-service:${DockerImageTag}
