AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Notification Service Lambda using existing SQS queue and IAM role

Resources:

  NotificationFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: NotificationFunction
      Handler: lambda.handler
      Runtime: nodejs20.x
      MemorySize: 512
      Timeout: 10
      Role: arn:aws:iam::326993352985:role/MedSafe-NotificationService
      CodeUri: dist/
      Environment:
        Variables:
          NODE_ENV: production
          DYNAMO_TABLE_NAME: MedSafe-Events
          SQS_QUEUE_ARN: arn:aws:sqs:sa-east-1:326993352985:medsafe-auth-to-notification
      Events:
        NotificationQueueEvent:
          Type: SQS
          Properties:
            Queue: arn:aws:sqs:sa-east-1:326993352985:medsafe-auth-to-notification
