AWSTemplateFormatVersion: "2010-09-09"
Description: Notification Service Stack

Parameters:
  DeploymentBucket:
    Type: String
  S3Key:
    Type: String

Resources:

  NotificationLambda:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: medsafe-notification-service
      Handler: dist/lambda.handler
      Runtime: nodejs20.x
      Role: arn:aws:iam::326993352985:role/MedSafe-NotificationService

      Code:
        S3Bucket: !Ref DeploymentBucket
        S3Key: !Ref S3Key

  NotificationSQSTrigger:
    Type: AWS::Lambda::EventSourceMapping
    Properties:
      EventSourceArn: arn:aws:sqs:sa-east-1:326993352985:medsafe-auth-to-notification
      FunctionName: !Ref NotificationLambda
      BatchSize: 10
      Enabled: true
