name: Deploy Database Service API

on:
  push:
    branches:
      - Database-Service-PROD

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      # 3. Instalação das dependências
      - name: Install dependencies
        working-directory: apps/database-service
        run: npm install

      # 4. Build do projeto
      - name: Build project
        working-directory: apps/database-service
        run: npm run build

      # 5. Login no Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # 6. Build da imagem Docker
      - name: Build Docker image
        working-directory: apps/database-service
        run: |
          docker build -t devjoaosg/medsafe-database-service:latest .
          docker tag devjoaosg/medsafe-database-service:latest devjoaosg/medsafe-database-service:${{ github.sha }}

      # 7. Push da imagem
      - name: Push Docker image
        run: |
          docker push devjoaosg/medsafe-database-service:latest
          docker push devjoaosg/medsafe-database-service:${{ github.sha }}

      # 8. Configurar credenciais AWS
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: sa-east-1

      # 9. Deploy CloudFormation
      - name: Deploy CloudFormation
        run: |
          aws cloudformation deploy \
            --stack-name MedSafe-Database-Stack \
            --template-file apps/database-service/cloudformation.yml \
            --capabilities CAPABILITY_IAM \
            --parameter-overrides \
              DockerImageTag=${{ github.sha }} \
              DbConnectionString=${{ secrets.DB_CONNECTION_STRING }} \
              NodeEnv=production \
              Port=443 \
              ServiceName=database-service \
              FrontUrl=http://177.16.162.33 \
              DatabaseApiKey=${{ secrets.DATABSE_SERVICE_X_AUTH_SERVICE_API_KEY }} \
              JwtSecret=${{ secrets.JWT_SECRET }} \
              CorsOrigins=http://177.16.162.33 \
              RequestTimeoutMs=7000

      # 10. Logs CloudFormation
      - name: Show CloudFormation events
        run: |
          aws cloudformation describe-stack-events \
            --stack-name MedSafe-Database-Stack \
            --max-items 20

      # 11. Debug CloudFormation failure
      - name: Debug CloudFormation failure
        if: failure()
        run: |
          aws cloudformation describe-stack-events \
            --stack-name MedSafe-Database-Stack \
            --max-items 20
